package view;

import clases.TextPrompt;
import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

public class Login extends javax.swing.JFrame {

    public Login() {
        initComponents();
        
        setLocationRelativeTo(null);
        setResizable(false);
        setSize(700, 500);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Background = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Username = new jtextfieldround.JTextFieldRound();
        jPasswordFieldRound1 = new jtextfieldround.JPasswordFieldRound();
        jLabel_Footer = new javax.swing.JLabel();
        jLabel_Anwser = new javax.swing.JLabel();
        jButton_Acceder = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel_Exit = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Background.setBackground(new java.awt.Color(9, 53, 69));
        jPanel_Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INICIAR SESION");
        jPanel_Background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 700, 60));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sistema de gestion de información de Quark Tech Mobile");
        jPanel_Background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 700, 30));

        jTextField_Username.setBackground(new java.awt.Color(34, 73, 87));
        jTextField_Username.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextField_Username.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTextField_Username.setForeground(new java.awt.Color(240, 240, 240));
        jPanel_Background.add(jTextField_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        jPasswordFieldRound1.setBackground(new java.awt.Color(34, 73, 87));
        jPasswordFieldRound1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jPasswordFieldRound1.setForeground(new java.awt.Color(240, 240, 240));
        jPanel_Background.add(jPasswordFieldRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        jLabel_Footer.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel_Footer.setForeground(new java.awt.Color(240, 240, 240));
        jLabel_Footer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Footer.setText("Creado Por @BBCompany.ca");
        jPanel_Background.add(jLabel_Footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 700, -1));

        jLabel_Anwser.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel_Anwser.setForeground(new java.awt.Color(250, 250, 250));
        jLabel_Anwser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel_Background.add(jLabel_Anwser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 410, 50));

        jButton_Acceder.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Acceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Login btn dark.png"))); // NOI18N
        jButton_Acceder.setBorder(null);
        jButton_Acceder.setBorderPainted(false);
        jButton_Acceder.setContentAreaFilled(false);
        jButton_Acceder.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_Acceder.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Login btn ligth.png"))); // NOI18N
        jButton_Acceder.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Login btn ligth.png"))); // NOI18N
        jPanel_Background.add(jButton_Acceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 220, 60));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Vectors .png"))); // NOI18N
        jPanel_Background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 700, 90));

        jPanel_Exit.setBackground(new java.awt.Color(9, 53, 69));
        jPanel_Exit.setForeground(new java.awt.Color(255, 255, 255));
        jPanel_Exit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("X");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        jPanel_Exit.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        jPanel_Background.add(jPanel_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 30, 30));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Contraseña:");
        jPanel_Background.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 220, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Nombre de usuario:");
        jPanel_Background.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 220, -1));

        getContentPane().add(jPanel_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        
        jPanel_Exit.setBackground(Color.red);
        
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        
        jPanel_Exit.setBackground(new java.awt.Color(9, 53, 69));
        
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        
        System.exit(0);
        
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Acceder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_Anwser;
    private javax.swing.JLabel jLabel_Footer;
    private javax.swing.JPanel jPanel_Background;
    private javax.swing.JPanel jPanel_Exit;
    private jtextfieldround.JPasswordFieldRound jPasswordFieldRound1;
    private jtextfieldround.JTextFieldRound jTextField_Username;
    // End of variables declaration//GEN-END:variables
}
